language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install

script:
  - bin/phpunit
  - bin/behat
  - bin/infection
  - bin/phpcs
  - bin/phpstan analyse -l max -c phpstan.neon src/ tests/
