services:
    Star\Component\Document\Tests\App\Fixtures\ApplicationFixtureBuilder:
        arguments:
            - '@Star\Component\DomainEvent\Messaging\CommandBus'
            - '@Star\Component\DomainEvent\Messaging\QueryBus'
            - '@doctrine.dbal.default_connection'
        public: true
