parameters:
    app.install_dir: '%env(resolve:APP_INSTALL_DIR)%'
    app.install.data_file: 'db_%env(resolve:APP_ENV)%.data'

services:
    App\Installation\CreateDbWhenNotExists:
        arguments:
            - '%app.install_dir%'
            - '%app.install.data_file%'
        tags:
            - { name: app.installation_step }

    App\Installation\InstallationChecker:
        alias: App\Installation\CheckInstallationSteps

    App\Installation\InstallationStep:
        alias: App\Installation\CreateDbWhenNotExists

    App\Installation\CheckInstallationSteps:
        arguments:
            - !tagged_iterator app.installation_step
