services:
    app.query_bus:
        alias: Star\Component\DomainEvent\Messaging\QueryBus

    Star\Component\Document\Design\Domain\Messaging\Query\FindAllMyDocumentsHandler:
        arguments:
            - '@app.connection'
        tags:
            - { name: star.query_handler }
            - { name: star.event_listener }

    Star\Component\Document\Design\Domain\Messaging\Query\FindStructureForDocumentHandler:
        arguments:
            - '@app.connection'
        tags:
            - { name: star.query_handler }
