services:
    app.repository_document:
        class: Star\Component\Document\Design\Infrastructure\Persistence\Doctrine\DocumentEventStore
        arguments:
            - '@app.connection'
            - '@app.event_publisher'
            - '@app.event_serializer'

    app.connection:
        alias: doctrine.dbal.default_connection
